import {
  Sparkles, LayoutDashboard, Users, FileText, Calendar,
  Video, Globe, Bot, FileText as FileTextAlt, Mail,
  Settings, MessageCircle,
} from 'lucide-react';

const TUTORIAL_STEPS = [
  {
    id: 'welcome', icon: Sparkles, iconColor: 'text-primary', bgColor: 'from-secondary to-white',
    title: 'ברוכה הבאה! 🌟',
    content: 'זה סיור קצר שיכיר לך את המערכת.\nכל שלב מקפיץ אותך לעמוד הרלוונטי, עם אפשרות לתרגל.\nאפשר לדלג, לחזור, או לצאת בכל רגע — הכפתור ? תמיד יחזיר אותך לכאן.',
    navigateTo: '/',
  },
  {
    id: 'dashboard', icon: LayoutDashboard, iconColor: 'text-primary', bgColor: 'from-secondary to-white',
    title: 'דשבורד — המסך הראשי',
    content: 'כאן רואים הכול במבט אחד.',
    bullets: [
      'לידים חדשים שממתינים לטיפול',
      'פגישות קרובות (היום + מחר)',
      'משימות פתוחות ודחופות',
      'התראות: כשלי תקשורת, פניות ממתינות',
    ],
    autoNote: 'הדשבורד מתעדכן בזמן אמת — כל שינוי בפנייה, פגישה או ליד נראה מיד.',
    practiceNote: 'תסתכלי על ההתראות בראש הדף — לחצי על אחת מהן.',
    navigateTo: '/',
  },
  {
    id: 'contacts', icon: Users, iconColor: 'text-coral', bgColor: 'from-[#FAF0ED] to-white',
    title: 'לקוחות — ניהול אנשי קשר',
    content: 'כאן מנהלים את כל הלקוחות והלידים.',
    bullets: [
      'חיפוש לפי שם, טלפון או מייל',
      'סינון לפי סטטוס, מקור וסוג שירות',
      'לחיצה על שם → כרטיס מלא עם כל הפרטים',
      'ייבוא מ-Excel, הוספה ידנית',
    ],
    autoNote: 'לידים מ-Google Sheets ומשורנס מתעדכנים אוטומטית.',
    adminNote: 'לחצי "+" כדי להוסיף ליד ידנית. בכרטיס הלקוח — כל הפניות, פגישות, מסמכים והיסטוריית תקשורת.',
    practiceNote: 'נסי לחפש איש קשר לפי שם, ואז לחצי עליו לכרטיס המלא.',
    navigateTo: '/contacts',
  },
  {
    id: 'service-requests', icon: FileText, iconColor: 'text-gold', bgColor: 'from-[#FBF1DE] to-white',
    title: 'פניות שירות',
    content: 'כל הפניות מכל הסוגים — מעקב שלב-אחר-שלב.',
    bullets: [
      'סוגי שירות: פרישה, היתכנות כלכלית, השקעות, איזון, מס, שנתי',
      'סטטוס: חדש → בטיפול → הצעת מחיר → פגישה → סגירה',
      'סינון לפי סטטוס, סוג שירות ותאריך',
      'לחיצה על פנייה → דף פרטים עם ציר זמן מלא',
    ],
    autoNote: 'פולו-אפ אוטומטי T+7 / T+14 / T+21 — הבוט שולח תזכורות ואחרי 3 ניסיונות מסלים לנציגה.',
    adminNote: 'את יכולה לשנות סטטוס ידנית, לשלוח הצעת מחיר, ולתאם פגישה ישירות מהדף.',
    practiceNote: 'נסי לסנן פניות לפי סטטוס "חדש" ולפתוח אחת מהן.',
    navigateTo: '/service-requests',
  },
  {
    id: 'meetings', icon: Calendar, iconColor: 'text-success', bgColor: 'from-[#EEF4E9] to-white',
    title: 'פגישות ומשימות',
    content: 'ניהול פגישות ומשימות — הכל במקום אחד.',
    bullets: [
      'פגישות: זום / פרונטלית (מודיעין/פ"ת) / טלפונית',
      'משימות: פולו-אפ, איסוף מסמכים, צ\'קליסט לפני/אחרי פגישה',
      'סינון לפי סטטוס, סוג, ותאריך',
    ],
    autoNote: 'תזכורות נשלחות אוטומטית: יום לפני ושעה לפני הפגישה (וואטסאפ).',
    adminNote: 'אחרי פגישה — סמני "בוצע" ומלאי סיכום. המערכת תפתח משימות המשך.',
    practiceNote: 'נסי ליצור פגישה חדשה או לסנן משימות לפי "פתוח".',
    navigateTo: '/meetings',
  },
  {
    id: 'marketing', icon: Mail, iconColor: 'text-[#B0455E]', bgColor: 'from-[#FAECF0] to-white',
    title: 'מרכז דיוור',
    content: 'שליחת קמפיינים מותאמים אישית.',
    bullets: [
      'ערוצים: מייל (Brevo) + וואטסאפ',
      'סוגים: ניוזלטר, ברכת יום הולדת, ביקורת גוגל, פולו-אפ אחרי פגישה',
      'עורך תבניות: כותרות, טקסט, תמונות, כפתורים',
      'מעקב: נפתח / נקלק / חזר (bounce)',
    ],
    autoNote: 'ברכות יום הולדת ותזכורות שנתיות נשלחות אוטומטית.',
    practiceNote: 'נסי לפתוח תבנית קיימת ולראות את העורך.',
    navigateTo: '/marketing',
  },
  {
    id: 'webinars', icon: Video, iconColor: 'text-primary', bgColor: 'from-secondary to-white',
    title: 'וובינרים — ניהול נרשמים',
    content: 'מעקב אחרי כל שלב מרגע ההרשמה ועד הפגישה.',
    bullets: [
      'נרשם → תזכורת → השתתף → קופון → שילם → פגישה',
      'רישום אוטומטי לזום + קישור הצטרפות אישי',
      'שליחת הקלטה אוטומטית למשתתפים',
      'קופון: סכום + אחוז הטבה — נשלח למשתתפים',
    ],
    autoNote: 'כל השלבים אוטומטיים: רישום לזום, תזכורות, הקלטה, קופון.',
    adminNote: 'סמני "שילם" או "פגישה נקבעה" ידנית כשצריך. אפשר לסנן לפי סוג וובינר.',
    practiceNote: 'נסי לסנן נרשמים לפי סוג וובינר ולראות את הסטטוסים.',
    navigateTo: '/webinars',
  },
  {
    id: 'landing-pages', icon: Globe, iconColor: 'text-[#2A6B6B]', bgColor: 'from-[#E6F4EF] to-white',
    title: 'דפי נחיתה',
    content: 'יצירת דפי נחיתה לוובינרים — עיצוב מותאם אישית.',
    bullets: [
      'טופס הרשמה עם שם, טלפון, מייל',
      'בלוקים גמישים: טקסט, תמונה, רשימת נקודות',
      'שאלות ותשובות, פרטי מרצה, הסכמה',
      'כתובת ייחודית (slug) לכל דף',
    ],
    autoNote: 'שינוי תאריך הוובינר מעדכן אוטומטית את כל הנרשמים ואת מועד הזום.',
    adminNote: 'לחצי "דף חדש" ומלאי את השדות. אחרי שמירה — הדף מיד פעיל בקישור.',
    practiceNote: 'נסי לפתוח דף נחיתה קיים ולערוך את הכותרת.',
    navigateTo: '/landing-pages',
  },
  {
    id: 'bot-content', icon: Bot, iconColor: 'text-primary', bgColor: 'from-secondary to-white',
    title: 'תוכן הבוט',
    content: 'עריכת ההודעות שהבוט שולח בוואטסאפ.',
    bullets: [
      'BotContent — הודעות עם placeholders (למשל {name}, {link})',
      'ServiceContent — קישורים: תשלום, הסכם, יומן Cal.com',
      'מחולק לפי קטגוריות: ברכה, תפריט, פולו-אפ, תזכורת, שגיאה',
    ],
    autoNote: 'כל שינוי בהודעות נכנס לתוקף מיד — בלי צורך בריסטרט.',
    adminNote: 'ערכי הודעה קיימת או הוסיפי חדשה. שימי לב ל-placeholders ({name}, {link}) — הם מוחלפים אוטומטית.',
    practiceNote: 'נסי ללחוץ על הודעה קיימת ולראות את ה-placeholders שבתוכה.',
    navigateTo: '/bot-content',
  },
  {
    id: 'bot-flows', icon: MessageCircle, iconColor: 'text-[#2A6B6B]', bgColor: 'from-[#E6F4EF] to-white',
    title: 'מסלולי הבוט 🤖',
    content: 'הבוט מנהל שני מסלולים עיקריים:',
    flows: [
      { name: '🛤️ מסלול כללי', desc: 'ליד חדש → זיהוי שירות → שאלון שורנס → הצעת מחיר → פגישה → פולו-אפ → סגירה.' },
      { name: '🎥 מסלול וובינר', desc: 'הרשמה → תזכורות → נוכחות → קופון → תשלום → פגישה.' },
    ],
    bullets: [
      '📋 זיהוי שירות — הבוט שואל שאלות ומזהה סוג שירות',
      '📝 שאלון שורנס — שליחת קישור + מעקב עד מילוי',
      '💰 הצעת מחיר — הסכם דיגיטלי + קישור תשלום',
      '📅 תיאום פגישה — קישור Cal.com (זום / פרונטלית / טלפונית)',
      '🔄 פולו-אפ — T+7 / T+14 / T+21 + הסלמה',
      '👩‍💼 הסלמה — העברה לנציגה אנושית + התראה',
    ],
    autoNote: 'הבוט עונה בעברית בלבד ולעולם לא אוסף פרטי אשראי.',
    tip: 'פירוט מלא של כל מסלול נמצא ב: הגדרות → מדריך שימוש.',
    navigateTo: '/bot-content',
  },
  {
    id: 'service-content', icon: FileTextAlt, iconColor: 'text-coral', bgColor: 'from-[#FAF0ED] to-white',
    title: 'ניהול תוכן — קישורים',
    content: 'מחסן הקישורים שהבוט שולח.',
    bullets: [
      'קישורי תשלום (הוראת קבע, מקדמה)',
      'קישורי הסכמים ומסמכים דיגיטליים',
      'קישורי יומן Cal.com לתיאום פגישות',
      'קישורי זום לוובינרים (לפי סוג)',
      'כל קישור משויך לסוג שירות ותת-סוג',
    ],
    adminNote: 'הוסיפי או ערכי קישור — הוא ייכנס מיד לשימוש בהודעות הבוט.',
    practiceNote: 'נסי למצוא את קישור התשלום של "ייעוץ פרישה" ולוודא שהוא תקין.',
    navigateTo: '/service-content',
  },
  {
    id: 'settings', icon: Settings, iconColor: 'text-gold', bgColor: 'from-[#FBF1DE] to-white',
    title: 'הגדרות המערכת',
    content: 'כל הגדרות המערכת — בטאבים.',
    bullets: [
      'כללי — הגדרות בוט, אוטומציות, SLA, הרשאות',
      'הגדרות מערכת — מיילים, קישורים, פרמטרים',
      'לוג תקשורת — כל ההודעות שנשלחו/נכשלו',
      'קופונים — הגדרות קופון לכל סוג וובינר',
      'כלי בדיקה — איפוס משתמש טסט',
      'בדיקת בוט — סימולטור שיחה חיה',
      'מדריך שימוש — הסבר מפורט (את כאן! 📖)',
    ],
    practiceNote: 'נסי לעבור על הטאבים ולהכיר את ההגדרות השונות.',
    navigateTo: '/settings',
  },
  {
    id: 'done', icon: Sparkles, iconColor: 'text-primary', bgColor: 'from-secondary to-white',
    title: 'סיימת! 🎉',
    content: 'את מכירה את המערכת.\nהבוט עונה אוטומטית, התהליכים רצים לבד, ואת מנהלת הכול מכאן.\n\nהכפתור ? תמיד זמין לסיור חוזר, והמדריך המפורט נמצא בהגדרות → מדריך שימוש.',
    navigateTo: '/',
  },
];

export default TUTORIAL_STEPS;